/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class LibraryTest {
    public static void main(String[] args) {
//        ChromeOptions options = new ChromeOptions();
//        options.setCapability();

        //For ggogle chrome browser automation
        System.setProperty("webdriver.chrome.driver", "libs/chromedriver");
        WebDriver driver = new ChromeDriver();

        //Navigate to url
        driver.get("https://www.google.com");

        driver.findElement(By.name("q")).sendKeys("Here is my first action !!!");

        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        driver.close();
        driver.quit();

        //For firefox config
//        System.getProperty("webdriver.gecko.driver", "driver path")
//        WebDriver driver = new FirefoxDriver();

        //for safari browser
//        WebDriver driver = new SafariDriver();

    }

}
